### ISSUE TITLE
[bug] Typing wrongfully expect toBeInTheDocument() to be awaitable

### ISSUE THREAD

**Issue by ueat-benoitt** [storybookjs/jest#39]
**Describe the bug**
When upgrading the library to the latest version, it expects expect(...).toBeInTheDocument() to return a promise. The return type should be `void` but is now `Promise<void>` while it should not be awaited. 

This seems to be related to https://github.com/storybookjs/jest/commit/ffdc9e4d3a311beb42b633945f4e40797a2836f3

**To Reproduce**
1. Update to the latest version
2. Enable @typescript-eslint/no-floating-promises ESLint rule
3. Add an expect(...).toBeInTheDocument()
4. Run ESLint and see the following error: `error  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises`

**Comment by kasperpeulen** [comment]
In storybook, `exect(..).toBeInTheDocument` must be await-ed!
It allows you to step back and forth through your interactions using the debugger.

**Comment by yannbf** [comment]
Hey @ueat-benoitt, thanks for going through the effort of explaining your use case and to put a reproduction.

Both @storybook/testing-library and @storybook/jest are packages which wrap other libraries, but instruments them. This instrumentation happens internally, and turns each of their methods into promises. There are multiple reasons to that:
1. So these steps can be canceled when needed
2. So these steps can be paused when needed
3. So the play function can be resolved at the right moment.

Now some more context regarding the aforementioned:

These libraries work in tandem with @storybook/addon-interactions, which provides a panel that helps you visualize the steps you wrote, but also to be able to step back and forth through them. This is only possible if you await each step you write.

If you're using visual regression tools like Chromatic, or the storybook test-runner with image snapshot plugins, you must await your steps, including expect ones, so that the snapshot occurs at the right moment, else you might have race conditions which may cause unexpected behavior.

If you're using the eslint plugin for Storybook (which we recommend), there are rules in place to enforce awaiting the steps as well.

I hope this helps clear things up, we'll work on improving the documentation to make this clearer!

**Comment by ueat-benoitt** [comment]
@yannbf Thank you so much for the explaination. We do use await on everything except on `except()` because with RTL you usually don't. I remember adding await on DOM interactions fixed a lot of flaky tests in Chromatic a few months ago.

I just noticed it is [documented here](https://storybook.js.org/docs/react/writing-tests/interaction-testing#write-an-interaction-test) but very easy to miss because of how unusual it is.

Thank you for your help, I love using Chromatic every day ❤️
