### ISSUE TITLE
[bug] Installation error, cannot find @storybook/expect@storybook-jest.

### ISSUE THREAD

**Issue by ImmanuelCurrah** [storybookjs/jest#51]
**Describe the bug**
Installing throws error, npm ERR! notarget No matching version found for @storybook/expect@storybook-jest.

**To Reproduce**
npm i @storybook/jest throws the error above. I am not sure why in the package.json the dependency is written this way: 
"dependencies": {
    "@storybook/expect": "storybook-jest",
    
I do not see a version named storybook-jest in the @storybook/expect repo.

**Expected behavior**

**Screenshots**

**System**
storybook@7.6.1

**Additional context**

**Comment by IanVS** [comment]
There is a `storybook-jest` npm tag, you can see it here: https://www.npmjs.com/package/@storybook/expect?activeTab=versions

Maybe there was a network blip or npm was having troubles.  I'd suggest trying to install it again.

And actually, I'd suggest using `@storybook/test` instead of this package anyway.  It's based on vitest, is a bit smaller, and has the testing-library tools as well, so you only need one storybook package instead of two.

https://storybook.js.org/blog/storybook-test/

**Comment by ImmanuelCurrah** [comment]
Okay I see that, confusing. Why use the tag rather than just specify the version? Installing it still isn't working for me. 

@Storybook/test does though, I will try and use that first. Thanks!

**Comment by yannbf** [comment]
Hey everyone! In Storybook 8, this package functionality has been integrated to a new package called `@storybook/test`, which uses Vitest APIs for an improved experience. This issue should be solved or maybe it's not applicable anymore.

When upgrading to Storybook 8 with `npx storybook@latest upgrade`, you will get prompted and will get an automigration for the new package. Please migrate when you can! Thanks a lot <3
